sudo: required

language: go

services:
  - docker

go:
  - 1.5

env:
  - TRAVIS_NODE_VERSION="0.12"

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm i -g newman@1.3.0

script:
  - ./run-tests.sh

addons:
  hosts:
    - dockerhost
